pub mod buffer;
pub mod cursor;
pub mod history;
pub mod message;
pub mod context_optimizer;
pub mod integration;
pub mod conversation_engine;
pub mod gemini_architecture;
pub mod retry_handler;
pub mod response_validation;
pub mod tool_executor;
pub mod routing_strategy;
pub mod streaming;
pub mod hooks;
pub mod routing_strategies;
pub mod message_history;
pub mod error_recovery;
pub mod streaming_optimizer;
pub mod token_calculator;
pub mod logger;
pub mod performance_optimizer;
pub mod chat_orchestrator;
pub mod health_check;
pub mod vibe_coding;
pub mod ai_agent;

pub use conversation_engine::{ConversationEngine, ConversationContext, UserIntent};

pub use gemini_architecture::{GeminiArchitecture, CompositeRouter};

pub use retry_handler::{RetryConfig, RetryHandler};
pub use routing_strategy::{RoutingDecision, RoutingStrategy};
pub use hooks::HookManager;
pub use message_history::MessageHistory;
pub use error_recovery::ErrorRecovery;
pub use streaming_optimizer::StreamingOptimizer;
pub use token_calculator::TokenCalculator;
pub use context_optimizer::ContextWindowOptimizer;
pub use chat_orchestrator::ChatOrchestrator;
pub use ai_agent::{AIAgent, AIAgentConfig, AgentResponse, AgentStatus, convert_to_chat_messages};